import AppKit
import ApplicationServices
import Carbon.HIToolbox
import PlumeKit

/// Inserts the text into the active field: clipboard + simulated ⌘V, then restoration.
/// Can also read what surrounds the cursor and what is selected, through accessibility.
enum Paster {
    /// macOS only allows key simulation for apps checked in "Accessibility".
    static var isTrusted: Bool { AXIsProcessTrusted() }

    /// Markers recognized by clipboard managers (Paste, Maccy, Raycast…):
    /// a dictation has no place in their history.
    private static let transientTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func requestTrust() {
        let key = kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String
        AXIsProcessTrustedWithOptions([key: true] as CFDictionary)
    }

    /// - Parameter transient: the text is just passing through. It is written with its markers in a
    ///   single step: a manager reading in between would keep it without seeing them.
    /// - Parameter pasteboard: the general pasteboard, except in tests.
    static func copy(_ text: String, transient: Bool = false, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            for type in transientTypes { item.setData(Data(), forType: type) }
        }
        pasteboard.writeObjects([item])
    }

    /// Prepares the paste, simulating nothing on the keyboard: keeps what will have to be restored (`nil`
    /// if nothing will be), then writes the dictation.
    static func stage(
        _ text: String, restoreClipboard: Bool, on pasteboard: NSPasteboard = .general
    ) -> [NSPasteboardItem]? {
        let saved = restoreClipboard ? snapshot(pasteboard) : nil
        // Restored right after: clipboard managers (Maccy, Raycast…) don't keep
        // content marked transient, so the dictation isn't added to their history.
        copy(text, transient: saved != nil, to: pasteboard)
        return saved
    }

    /// Puts back the content from before the paste. If the user copied something else in the meantime
    /// (`changeCount` moved), leave everything alone.
    static func restore(
        _ saved: [NSPasteboardItem], to pasteboard: NSPasteboard = .general, ifUnchangedSince marker: Int
    ) {
        guard pasteboard.changeCount == marker else { return }
        pasteboard.clearContents()
        if !saved.isEmpty { pasteboard.writeObjects(saved) }
    }

    /// - Parameter typing: types the text key by key instead of going through ⌘V, for
    ///   apps that don't paste (remote desktop, some games or terminals).
    /// - Returns: `true` if the paste was started, `false` if the text is only copied
    ///   (Accessibility permission missing).
    @discardableResult
    static func paste(_ text: String, restoreClipboard: Bool, typing: Bool = false) -> Bool {
        let pasteboard = NSPasteboard.general
        guard isTrusted else {
            copy(text)
            return false
        }
        if typing {
            type(text)
            return true
        }
        let saved = stage(text, restoreClipboard: restoreClipboard, on: pasteboard)
        let marker = pasteboard.changeCount
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            post(key: keyCode(for: "V"), flags: .maskCommand)
            guard let saved else { return }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) {
                restore(saved, to: pasteboard, ifUnchangedSince: marker)
            }
        }
        return true
    }

    /// Presses Return, once the text is in place ("appuie sur Entrée", or an app rule).
    static func pressReturn(after delay: TimeInterval = 0.25) {
        guard isTrusted else { return }
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            post(key: CGKeyCode(kVK_Return), flags: [])
        }
    }

    /// Types the text as on a keyboard, in batches: each event can carry up to
    /// twenty Unicode characters. Also used to write as the dictation goes, without touching the
    /// clipboard.
    static func type(_ text: String) {
        guard isTrusted, !text.isEmpty else { return }
        let source = CGEventSource(stateID: .combinedSessionState)
        // A line break is typed ⇧↩: a plain ↩ would send the message in Slack or Messages.
        for (index, line) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            if index > 0 { post(key: CGKeyCode(kVK_Return), flags: .maskShift) }
            let units = Array(line.utf16)
            var offset = 0
            while offset < units.count {
                let chunk = Array(units[offset..<min(offset + 20, units.count)])
                let down = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true)
                let up = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
                down?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: chunk)
                up?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: chunk)
                down?.post(tap: .cghidEventTap)
                up?.post(tap: .cghidEventTap)
                offset += 20
                usleep(3_000)
            }
        }
    }

    /// Erases the last `count` typed characters (the live text was corrected).
    static func erase(_ count: Int) {
        guard isTrusted, count > 0 else { return }
        for _ in 0..<count {
            post(key: CGKeyCode(kVK_Delete), flags: [])
            usleep(1_500)
        }
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func post(key: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// Code of the key that carries this letter: it isn't in the same place on all
    /// layouts (Bépo, Dvorak).
    private static func keyCode(for letter: String) -> CGKeyCode {
        CGKeyCode((0..<50).first { HotkeyManager.keyName($0) == letter } ?? kVK_ANSI_V)
    }

    // MARK: - Reading the active field

    /// The element that has keyboard focus in the frontmost application.
    private static func focusedElement() -> AXUIElement? {
        guard isTrusted, let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let application = AXUIElementCreateApplication(app.processIdentifier)
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(application, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let element = focused
        else { return nil }
        return (element as! AXUIElement)
    }

    private static func string(_ attribute: String, of element: AXUIElement) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success else { return nil }
        return value as? String
    }

    private static func range(_ attribute: String, of element: AXUIElement) -> CFRange? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success, let value else { return nil }
        var range = CFRange()
        guard CFGetTypeID(value) == AXValueGetTypeID(), AXValueGetValue(value as! AXValue, .cfRange, &range) else { return nil }
        return range
    }

    private static func string(for range: CFRange, of element: AXUIElement) -> String? {
        var cfRange = range
        guard let parameter = AXValueCreate(.cfRange, &cfRange) else { return nil }
        var value: CFTypeRef?
        guard AXUIElementCopyParameterizedAttributeValue(
            element, kAXStringForRangeParameterizedAttribute as CFString, parameter, &value) == .success
        else { return nil }
        return value as? String
    }

    /// Whether a field is a password field. macOS reports one as role `AXTextField` with subrole
    /// `AXSecureTextField`, so the subrole is what matters; the role is checked too, for apps
    /// that report the value there.
    static func isSecure(role: String?, subrole: String?) -> Bool {
        let secure = kAXSecureTextFieldSubrole
        return role == secure || subrole == secure
    }

    private static func isSecure(_ element: AXUIElement) -> Bool {
        isSecure(role: string(kAXRoleAttribute, of: element), subrole: string(kAXSubroleAttribute, of: element))
    }

    /// A few characters on either side of the cursor, or `nil` if the app doesn't expose them
    /// (many web or Electron apps don't).
    static func insertionContext(reach: Int = 60) -> InsertionContext? {
        guard let element = focusedElement(), let selection = range(kAXSelectedTextRangeAttribute, of: element) else {
            return nil
        }
        // A password field can't be read.
        if isSecure(element) { return nil }
        let start = max(0, selection.location - reach)
        let before = string(for: CFRange(location: start, length: selection.location - start), of: element)
        var after = string(for: CFRange(location: selection.location + selection.length, length: reach), of: element)
        if after == nil {
            // End of text nearby: the requested range overshoots, retry with what remains.
            var count: CFTypeRef?
            if AXUIElementCopyAttributeValue(element, kAXNumberOfCharactersAttribute as CFString, &count) == .success,
                let total = count as? Int
            {
                let end = selection.location + selection.length
                after = total > end ? string(for: CFRange(location: end, length: total - end), of: element) : ""
            }
        }
        if before == nil, after == nil {
            // Last resort: the whole text, for fields that lack the range attribute.
            guard let value = string(kAXValueAttribute, of: element) else { return nil }
            let units = Array(value.utf16)
            let location = min(max(0, selection.location), units.count)
            let end = min(location + max(0, selection.length), units.count)
            return InsertionContext(
                before: String(utf16CodeUnits: Array(units[max(0, location - reach)..<location]), count: min(location, reach)),
                after: String(utf16CodeUnits: Array(units[end..<min(units.count, end + reach)]), count: min(units.count - end, reach)))
        }
        return InsertionContext(before: before ?? "", after: after ?? "")
    }

    /// The selected text in the frontmost app: through accessibility, otherwise through a discreet ⌘C
    /// (the clipboard is restored right after).
    static func selectedText() async -> String {
        // A password field has no selection to read, and ⌘C must not be tried on it.
        if let element = focusedElement(), isSecure(element) { return "" }
        if let element = focusedElement(), let selected = string(kAXSelectedTextAttribute, of: element),
            !selected.isEmpty
        {
            return selected
        }
        guard isTrusted else { return "" }
        let pasteboard = NSPasteboard.general
        let saved = snapshot(pasteboard)
        let marker = pasteboard.changeCount
        post(key: keyCode(for: "C"), flags: .maskCommand)
        try? await Task.sleep(nanoseconds: 180_000_000)
        var text = ""
        if pasteboard.changeCount != marker { text = pasteboard.string(forType: .string) ?? "" }
        pasteboard.clearContents()
        if !saved.isEmpty { pasteboard.writeObjects(saved) }
        return text
    }
}
