import AppKit
import ApplicationServices
import Carbon.HIToolbox
import PlumeKit

/// Insère le texte dans le champ actif : presse-papiers + ⌘V simulé, puis restauration.
/// Sait aussi lire ce qui entoure le curseur et ce qui est sélectionné, par l'accessibilité.
enum Paster {
    /// macOS n'autorise la simulation de touches qu'aux apps cochées dans « Accessibilité ».
    static var isTrusted: Bool { AXIsProcessTrusted() }

    /// Marqueurs reconnus par les gestionnaires de presse-papiers (Paste, Maccy, Raycast…) :
    /// une dictée n'a rien à faire dans leur historique.
    private static let transientTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func requestTrust() {
        let key = kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String
        AXIsProcessTrustedWithOptions([key: true] as CFDictionary)
    }

    /// - Parameter transient: le texte ne fait que passer. Il est écrit avec ses marques en une
    ///   seule fois : un gestionnaire qui lirait entre les deux le garderait sans les voir.
    static func copy(_ text: String, transient: Bool = false) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            for type in transientTypes { item.setData(Data(), forType: type) }
        }
        pasteboard.writeObjects([item])
    }

    /// - Parameter typing: tape le texte touche par touche au lieu de passer par ⌘V, pour les
    ///   apps qui ne collent pas (bureau à distance, certains jeux ou terminaux).
    /// - Returns: `true` si le collage a été lancé, `false` si le texte est seulement copié
    ///   (autorisation Accessibilité manquante).
    @discardableResult
    static func paste(_ text: String, restoreClipboard: Bool, typing: Bool = false) -> Bool {
        let pasteboard = NSPasteboard.general
        guard isTrusted else {
            copy(text)
            return false
        }
        if typing {
            type(text)
            return true
        }
        let saved = restoreClipboard ? snapshot(pasteboard) : nil
        // Rétabli juste après : les gestionnaires de presse-papiers (Maccy, Raycast…) ne retiennent
        // pas un contenu marqué éphémère, la dictée ne s'ajoute pas à leur historique.
        copy(text, transient: saved != nil)
        let marker = pasteboard.changeCount
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            post(key: keyCode(for: "V"), flags: .maskCommand)
            guard let saved else { return }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) {
                // Si l'utilisateur a copié autre chose entre-temps, on ne touche à rien.
                guard pasteboard.changeCount == marker else { return }
                pasteboard.clearContents()
                if !saved.isEmpty { pasteboard.writeObjects(saved) }
            }
        }
        return true
    }

    /// Appuie sur Entrée, une fois le texte en place (« appuie sur Entrée », ou règle de l'app).
    static func pressReturn(after delay: TimeInterval = 0.25) {
        guard isTrusted else { return }
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            post(key: CGKeyCode(kVK_Return), flags: [])
        }
    }

    /// Tape le texte comme au clavier, par paquets : chaque événement peut porter jusqu'à
    /// vingt caractères Unicode. Sert aussi à écrire au fil de la dictée, sans toucher au
    /// presse-papiers.
    static func type(_ text: String) {
        guard isTrusted, !text.isEmpty else { return }
        let source = CGEventSource(stateID: .combinedSessionState)
        // Un saut de ligne se tape ⇧↩ : un simple ↩ enverrait le message dans Slack ou Messages.
        for (index, line) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            if index > 0 { post(key: CGKeyCode(kVK_Return), flags: .maskShift) }
            let units = Array(line.utf16)
            var offset = 0
            while offset < units.count {
                let chunk = Array(units[offset..<min(offset + 20, units.count)])
                let down = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true)
                let up = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
                down?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: chunk)
                up?.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: chunk)
                down?.post(tap: .cghidEventTap)
                up?.post(tap: .cghidEventTap)
                offset += 20
                usleep(3_000)
            }
        }
    }

    /// Efface les `count` derniers caractères tapés (le direct s'est corrigé).
    static func erase(_ count: Int) {
        guard isTrusted, count > 0 else { return }
        for _ in 0..<count {
            post(key: CGKeyCode(kVK_Delete), flags: [])
            usleep(1_500)
        }
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func post(key: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// Code de la touche qui porte cette lettre : elle n'est pas au même endroit sur toutes les
    /// dispositions (Bépo, Dvorak).
    private static func keyCode(for letter: String) -> CGKeyCode {
        CGKeyCode((0..<50).first { HotkeyManager.keyName($0) == letter } ?? kVK_ANSI_V)
    }

    // MARK: - Lecture du champ actif

    /// L'élément qui a le focus clavier dans l'application au premier plan.
    private static func focusedElement() -> AXUIElement? {
        guard isTrusted, let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let application = AXUIElementCreateApplication(app.processIdentifier)
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(application, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let element = focused
        else { return nil }
        return (element as! AXUIElement)
    }

    private static func string(_ attribute: String, of element: AXUIElement) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success else { return nil }
        return value as? String
    }

    private static func range(_ attribute: String, of element: AXUIElement) -> CFRange? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success, let value else { return nil }
        var range = CFRange()
        guard CFGetTypeID(value) == AXValueGetTypeID(), AXValueGetValue(value as! AXValue, .cfRange, &range) else { return nil }
        return range
    }

    private static func string(for range: CFRange, of element: AXUIElement) -> String? {
        var cfRange = range
        guard let parameter = AXValueCreate(.cfRange, &cfRange) else { return nil }
        var value: CFTypeRef?
        guard AXUIElementCopyParameterizedAttributeValue(
            element, kAXStringForRangeParameterizedAttribute as CFString, parameter, &value) == .success
        else { return nil }
        return value as? String
    }

    /// Quelques caractères de part et d'autre du curseur, ou `nil` si l'app ne les expose pas
    /// (beaucoup d'apps web ou Electron ne le font pas).
    static func insertionContext(reach: Int = 60) -> InsertionContext? {
        guard let element = focusedElement(), let selection = range(kAXSelectedTextRangeAttribute, of: element) else {
            return nil
        }
        // Un champ de mot de passe ne se lit pas.
        if string(kAXRoleAttribute, of: element) == "AXSecureTextField" { return nil }
        let start = max(0, selection.location - reach)
        let before = string(for: CFRange(location: start, length: selection.location - start), of: element)
        var after = string(for: CFRange(location: selection.location + selection.length, length: reach), of: element)
        if after == nil {
            // Fin de texte proche : la plage demandée dépasse, on réessaie avec ce qui reste.
            var count: CFTypeRef?
            if AXUIElementCopyAttributeValue(element, kAXNumberOfCharactersAttribute as CFString, &count) == .success,
                let total = count as? Int
            {
                let end = selection.location + selection.length
                after = total > end ? string(for: CFRange(location: end, length: total - end), of: element) : ""
            }
        }
        if before == nil, after == nil {
            // Dernier recours : tout le texte, pour les champs qui n'ont pas l'attribut par plage.
            guard let value = string(kAXValueAttribute, of: element) else { return nil }
            let units = Array(value.utf16)
            let location = min(max(0, selection.location), units.count)
            let end = min(location + max(0, selection.length), units.count)
            return InsertionContext(
                before: String(utf16CodeUnits: Array(units[max(0, location - reach)..<location]), count: min(location, reach)),
                after: String(utf16CodeUnits: Array(units[end..<min(units.count, end + reach)]), count: min(units.count - end, reach)))
        }
        return InsertionContext(before: before ?? "", after: after ?? "")
    }

    /// Le texte sélectionné dans l'app au premier plan : par l'accessibilité, sinon par un ⌘C
    /// discret (le presse-papiers est remis en l'état juste après).
    static func selectedText() async -> String {
        if let element = focusedElement(), let selected = string(kAXSelectedTextAttribute, of: element),
            !selected.isEmpty
        {
            return selected
        }
        guard isTrusted else { return "" }
        let pasteboard = NSPasteboard.general
        let saved = snapshot(pasteboard)
        let marker = pasteboard.changeCount
        post(key: keyCode(for: "C"), flags: .maskCommand)
        try? await Task.sleep(nanoseconds: 180_000_000)
        var text = ""
        if pasteboard.changeCount != marker { text = pasteboard.string(forType: .string) ?? "" }
        pasteboard.clearContents()
        if !saved.isEmpty { pasteboard.writeObjects(saved) }
        return text
    }
}
