import AppKit
import Testing
@testable import Plume

/// What a dictation leaves on the pasteboard, without simulating anything on the keyboard.
/// Always a named pasteboard, never the general one: the user loses nothing during the tests.
@Suite("Pasteboard")
@MainActor
struct PasterTests {
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private func withPasteboard(_ body: (NSPasteboard) -> Void) {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("plume-tests-\(UUID().uuidString)"))
        defer { pasteboard.releaseGlobally() }
        body(pasteboard)
    }

    @Test func aDictationThatWillBeReplacedCarriesTransientMarks() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard)
            #expect(pasteboard.pasteboardItems?.count == 1)
            #expect(pasteboard.string(forType: .string) == "la dictée")
            #expect(pasteboard.types?.contains(Self.transient) == true)
            #expect(pasteboard.types?.contains(Self.autoGenerated) == true)
            #expect(saved?.count == 1)
            #expect(saved?.first?.string(forType: .string) == "contenu d'avant")
        }
    }

    @Test func aDictationThatStaysBelongsToClipboardManagers() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: false, on: pasteboard)
            #expect(saved == nil)
            #expect(pasteboard.string(forType: .string) == "la dictée")
            #expect(pasteboard.types?.contains(Self.transient) == false)
            #expect(pasteboard.types?.contains(Self.autoGenerated) == false)
        }
    }

    @Test func aPlainCopyCarriesNoMark() {
        withPasteboard { pasteboard in
            Paster.copy("texte", to: pasteboard)
            #expect(pasteboard.pasteboardItems?.count == 1)
            #expect(pasteboard.string(forType: .string) == "texte")
            #expect(pasteboard.types?.contains(Self.transient) == false)
        }
    }

    /// Everything comes back, not just the text: several items, several formats each. Rich
    /// text or an image must not turn back into plain text.
    @Test func previousContentComesBackAfterPasting() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            let first = NSPasteboardItem()
            first.setString("contenu d'avant", forType: .string)
            first.setString("<b>contenu d'avant</b>", forType: .html)
            let second = NSPasteboardItem()
            second.setString("deuxième élément", forType: .string)
            pasteboard.writeObjects([first, second])
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard) ?? []
            Paster.restore(saved, to: pasteboard, ifUnchangedSince: pasteboard.changeCount)
            let items = pasteboard.pasteboardItems ?? []
            #expect(items.count == 2)
            #expect(items.first?.string(forType: .string) == "contenu d'avant")
            #expect(items.first?.string(forType: .html) == "<b>contenu d'avant</b>")
            #expect(items.last?.string(forType: .string) == "deuxième élément")
            #expect(pasteboard.types?.contains(Self.transient) == false)
        }
    }

    @Test func anEmptyPasteboardBecomesEmptyAgain() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard)
            #expect(saved?.isEmpty == true)
            #expect(pasteboard.types?.contains(Self.transient) == true)
            Paster.restore(saved ?? [], to: pasteboard, ifUnchangedSince: pasteboard.changeCount)
            #expect(pasteboard.string(forType: .string) == nil)
        }
    }

    @Test func aCopyMadeInTheMeantimeStays() {
        withPasteboard { pasteboard in
            pasteboard.clearContents()
            pasteboard.setString("contenu d'avant", forType: .string)
            let saved = Paster.stage("la dictée", restoreClipboard: true, on: pasteboard) ?? []
            let marker = pasteboard.changeCount
            pasteboard.clearContents()
            pasteboard.setString("copié entre-temps", forType: .string)
            Paster.restore(saved, to: pasteboard, ifUnchangedSince: marker)
            #expect(pasteboard.string(forType: .string) == "copié entre-temps")
        }
    }
}

/// Smart insert never reads a password field. macOS reports one as role `AXTextField` with
/// subrole `AXSecureTextField`; the literals below are on purpose, so a wrong constant in the
/// implementation fails here.
@Suite("Secure field check")
struct SecureFieldTests {
    @Test(arguments: [
        ("AXTextField", "AXSecureTextField", true),  // a real password field
        ("AXSecureTextField", nil, true),  // an app that reports it as the role
        (nil, "AXSecureTextField", true),
        ("AXSecureTextField", "AXTextField", true),
        ("AXTextField", nil, false),
        ("AXTextField", "AXSearchField", false),
        ("AXTextArea", nil, false),
        ("AXTextField", "", false),
        (nil, nil, false),  // the app exposes neither: not treated as secure
        ("axsecuretextfield", nil, false),  // case-sensitive, like AX strings
    ] as [(String?, String?, Bool)])
    func secureFieldIsRecognised(role: String?, subrole: String?, expected: Bool) {
        #expect(Paster.isSecure(role: role, subrole: subrole) == expected)
    }
}
